---
- name: Create an s3 bucket on AWS with Ansible
  hosts: localhost
  connection: local   # no SSH, we want to use HTTP
  gather_facts: no

  vars_files:
      - vars/bucket_details.yml
      
  vars:
      access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"


  tasks:
    - name: Create an Amazon AWS S3 bucket
      s3_bucket:
        name: "{{ s3bucketname }}"    # default is "jellytoaster76"
        state: "{{ hereorthere }}"    # default is "present"
        aws_access_key: "{{ access_key }}"  # default is defined in ~/cred.zon
        aws_secret_key: "{{ secret_key }}"  # defautl is defined in ~/cred.zon
